apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdemo
  namespace: harsha
  labels:
    app: dotnetdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetdemo
  template:
    metadata:
      labels:
        app: dotnetdemo
    spec:
      containers:
      - name: dotnetdemo
        image: harshavardhankalluri.azurecr.io/dotnet:v1
        ports:
        - containerPort: 5000
      imagePullSecrets: 
      - name: harsha